use_frameworks!

target 'ICResourceKit_Example' do
    
    pod 'ICResourceKit', :path => '../'
    
    pod 'ICObserver', '0.1.2'
    pod 'GDataXML-HTML', :git => 'https://github.com/graetzer/GDataXML-HTML.git', :branch=>'master'
    pod 'ICFoundation', :git => 'git@github.com:IvanChan/ICFoundation.git', :branch=>'master'
end
